# Generated by Django 3.0.4 on 2020-05-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.IntegerField(help_text='省份id', primary_key=True, serialize=False)),
                ('province_name', models.CharField(help_text='省份名称', max_length=20)),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'Province',
                'ordering': ['province_id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.IntegerField(help_text='院校id', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='院校名称', max_length=128)),
                ('level_name', models.CharField(help_text='层次', max_length=128)),
                ('type_name', models.CharField(help_text='类别', max_length=128)),
                ('belong', models.CharField(help_text='隶属部门', max_length=128)),
                ('f985', models.IntegerField(help_text='985')),
                ('f211', models.IntegerField(help_text='211')),
                ('city', models.CharField(help_text='城市', max_length=128)),
                ('county', models.CharField(help_text='地区', max_length=128)),
                ('nature_name', models.CharField(help_text='公办或民办', max_length=128)),
                ('dual_class_name', models.CharField(help_text='双一流', max_length=128)),
                ('hot', models.IntegerField(help_text='热度')),
                ('logo', models.CharField(help_text='校徽', max_length=256)),
                ('num_subject', models.IntegerField(help_text='重点学科')),
                ('num_master', models.IntegerField(help_text='硕士点')),
                ('num_doctor', models.IntegerField(help_text='博士点')),
                ('short', models.CharField(help_text='简称', max_length=256)),
                ('rank', models.CharField(help_text='排名', max_length=256)),
                ('email', models.CharField(help_text='邮箱', max_length=256)),
                ('address', models.CharField(help_text='地址', max_length=256)),
                ('phone', models.CharField(help_text='电话', max_length=256)),
                ('site', models.CharField(help_text='网站', max_length=256)),
                ('create_date', models.CharField(help_text='建校日期例如1990', max_length=256)),
                ('area', models.CharField(help_text='地区', max_length=256)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='School.Province')),
            ],
            options={
                'verbose_name': '院校信息',
                'verbose_name_plural': '院校信息',
                'db_table': 'School',
                'ordering': ['school_id'],
            },
        ),
        migrations.CreateModel(
            name='SchoolLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='年份')),
                ('subject_type', models.CharField(help_text='类别', max_length=128)),
                ('score', models.IntegerField(help_text='分数')),
                ('province', models.ForeignKey(help_text='省份id', on_delete=django.db.models.deletion.CASCADE, to='School.Province')),
                ('school', models.ForeignKey(help_text='院校id', on_delete=django.db.models.deletion.CASCADE, to='School.School')),
            ],
            options={
                'verbose_name': '院校分数线',
                'verbose_name_plural': '院校分数线',
                'db_table': 'SchoolLine',
                'ordering': ['school_id', 'province_id'],
            },
        ),
        migrations.CreateModel(
            name='ProvinceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='年份')),
                ('subject_type', models.CharField(help_text='类别', max_length=128)),
                ('batch', models.CharField(help_text='批次', max_length=128)),
                ('score', models.IntegerField(help_text='分数')),
                ('province', models.ForeignKey(help_text='省份id', on_delete=django.db.models.deletion.CASCADE, to='School.Province')),
            ],
            options={
                'verbose_name': '省分数线',
                'verbose_name_plural': '省分数线',
                'db_table': 'ProvinceLine',
                'ordering': ['province_id', 'year'],
            },
        ),
    ]
