# Generated by Django 3.0.4 on 2020-05-06 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='年份')),
                ('subject_type', models.CharField(help_text='类别', max_length=128)),
                ('batch', models.CharField(help_text='批次', max_length=128)),
                ('province', models.ForeignKey(help_text='省份id', on_delete=django.db.models.deletion.CASCADE, to='School.Province')),
            ],
            options={
                'verbose_name': '身份批次',
                'verbose_name_plural': '身份批次',
                'db_table': 'ProvinceBatch',
                'ordering': ['year', 'province_id'],
            },
        ),
    ]
