# Generated by Django 3.0.4 on 2020-05-06 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0002_provincebatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincebatch',
            options={'ordering': ['year', 'province_id'], 'verbose_name': '省份批次', 'verbose_name_plural': '省份批次'},
        ),
    ]
