# Generated by Django 3.0.4 on 2020-05-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_auto_20200506_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='provincebatch',
            name='score',
            field=models.IntegerField(default=0, help_text='分数线'),
        ),
    ]
