# Generated by Django 3.0.4 on 2020-05-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Special',
            fields=[
                ('special_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_1', models.CharField(help_text='分类1', max_length=64)),
                ('level_2', models.CharField(help_text='分类2', max_length=64)),
                ('level_3', models.CharField(help_text='分类3', max_length=64)),
                ('special_name', models.CharField(help_text='专业名称', max_length=256)),
                ('hot', models.IntegerField(help_text='专业热度')),
                ('limit_year', models.CharField(help_text='所学年份', max_length=256)),
                ('degree', models.CharField(help_text='授予学位名称', max_length=256)),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'db_table': 'Special',
                'ordering': ['level_1', 'level_2', 'level_3'],
            },
        ),
    ]
