# Generated by Django 3.0.4 on 2020-05-10 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profession', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='special',
            options={'ordering': ['level_1', 'level_2', 'level_3', 'hot'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
    ]
