# Generated by Django 3.0.4 on 2020-05-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(help_text='用户名', max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, help_text='密码', max_length=128)),
                ('subject_type', models.CharField(default='1', help_text='类别', max_length=128)),
                ('score', models.IntegerField(default=500, help_text='高考分数')),
                ('people_type', models.CharField(max_length=128)),
                ('province', models.ForeignKey(default=44, help_text='省份/外键', on_delete=django.db.models.deletion.CASCADE, to='School.Province')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'User',
                'ordering': ['username'],
            },
        ),
    ]
